#!/usr/bin/env python3
"""Cwd-independent launcher for the agentic-orchestrator MCP stdio server.

Host MCP configs generated by bootstrap invoke this file by absolute path
instead of relying on ``python -m scripts.orchestrator.mcp_server`` from a
specific cwd. This script inserts the plugin root on ``sys.path`` before
importing ``scripts.orchestrator``.
"""

from __future__ import annotations

import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_SCRIPTS_DIR = os.path.dirname(_HERE)
_REPO_ROOT = os.path.dirname(_SCRIPTS_DIR)

for _path in (_REPO_ROOT, _SCRIPTS_DIR):
    if _path not in sys.path:
        sys.path.insert(0, _path)

from scripts.orchestrator.mcp_server import main

if __name__ == "__main__":
    main()
