#!/usr/bin/env python3
"""Render the harness's BMad Build steps into the plugin with BMad's own renderer.

    render_bmad.py            render plugins/…/skills/bmad-build/ from its templates
    render_bmad.py --check    fail if the shipped files differ from a fresh render

BMad renders its workflow in the user's project at run time, which needs Jinja2 there. The harness
renders once, here, with the vendored `render_skill.render` unchanged: it stages the templates from
`vendor/bmad/harness/bmad-build/` with the skill's `customize.toml`, renders them against a
throwaway project, and turns the absolute paths a run-time render would bake in back into the
placeholders the steps resolve when they run (`{skill-root}`, `{output_folder}`, and links to
sibling steps). Needs Jinja2 (requirements-dev.txt).
"""

from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PLUGIN = ROOT / "plugins" / "monolithic-dev-harness"
SKILL = PLUGIN / "skills" / "bmad-build"
SOURCES = PLUGIN / "vendor" / "bmad" / "harness" / "bmad-build"
SCRIPTS = PLUGIN / "vendor" / "bmad" / "skills" / "bmad" / "scripts"
# Stage 0 plans and hands off; the harness owns implementation and review.
STEPS = (
    "workflow.md",
    "step-01-clarify-and-route.md",
    "step-02-plan.md",
    "plan-template.md",
)
PINS = ('workflow.route="full"', 'workflow.review="none"')
NOTICE = (
    "<!-- Generated by scripts/render_bmad.py from vendor/bmad/harness/bmad-build/{name}. "
    "Edit the source and render again. -->\n"
)


def render() -> dict[str, str]:
    """Every shipped step, as the plugin should contain it."""
    sys.path.insert(0, str(SCRIPTS))
    import render_skill  # the vendored BMad renderer, unchanged

    with tempfile.TemporaryDirectory() as temp:
        staged = Path(temp) / "skills" / "bmad-build"
        staged.mkdir(parents=True)
        for name in STEPS:
            shutil.copy2(SOURCES / name, staged / name)
        shutil.copy2(SKILL / "customize.toml", staged / "customize.toml")
        project = Path(temp) / "project"
        (project / "_bmad").mkdir(parents=True)
        (project / "_bmad" / "config.toml").write_text(
            '[core]\noutput_folder = "{output_folder}"\n', encoding="utf-8"
        )
        entry = render_skill.render(project, staged, assignments=list(PINS))
        generation = entry.parent
        return {
            name: _relative(
                (generation / name).read_text(encoding="utf-8"),
                generation,
                staged.resolve(),
                name,
            )
            for name in STEPS
        }


def _relative(text: str, generation: Path, staged: Path, name: str) -> str:
    text = text.replace(generation.as_posix() + "/", "")
    text = text.replace(staged.as_posix(), "{skill-root}")
    if text.startswith("---\n"):
        close = text.index("\n---\n", 4) + 5
        return text[:close] + NOTICE.format(name=name) + text[close:]
    return NOTICE.format(name=name) + text


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    stale = [
        name
        for name, text in expected.items()
        if not (SKILL / name).is_file()
        or (SKILL / name).read_text(encoding="utf-8") != text
    ]
    if args.check:
        for name in stale:
            print(f"stale: skills/bmad-build/{name}; run scripts/render_bmad.py")
        return 1 if stale else 0
    for name, text in expected.items():
        (SKILL / name).write_text(text, encoding="utf-8")
    print(f"rendered {len(expected)} files into {SKILL.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
